# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data_analysis_nbdev',
                'doc_host': 'https://parth4594.github.io',
                'git_url': 'https://github.com/parth4594/data_analysis_nbdev',
                'lib_path': 'data_analysis_nbdev'},
  'syms': {'data_analysis_nbdev.core': {'data_analysis_nbdev.core.foo': ('core.html#foo', 'data_analysis_nbdev/core.py')}}}
